### PR TITLE
Use 2 spaces instead of 4

### PR DESCRIPTION
**Pull request by Unisay**
As per https://github.com/tricycle/bellroy/pull/3030

### CODE REVIEW

**Comment by everlaat** [comment]
Let’s not fork elm-format. 

The beauty of elm-format is that 99% of the elm users/packages use the same elm-format with zero configuration options.

**Comment by michaelwebb76** [comment]
This PR in its current form is not something that would ever be merged back into upstream - should the approach be that this value becomes configurable instead?

**Comment by Unisay** [comment]
> This PR in its current form is not something that would ever be merged back into upstream 

Correct. More than that, I believe that any PR that changes indentation depth will ever be merged upstream (hence the fork). The idea of elm designers is to decide one and for all what indentation to use, nail it down and avoid ever returning to discussions about changing it.

> should the approach be that this value becomes configurable instead?

The `elm-format` is written in a way that its intentionally not configurable. While its possible to make it configurable - it would be super hard to adjust all the tests to use that value as its hard-coded everywhere.

**Comment by Unisay** [comment]
> Let’s not fork elm-format.

I am confused now:
Here https://github.com/tricycle/bellroy/pull/3030 we agreed to fork `elf-format` and you didn't object, so I went ahead, spent time doing it and now, after the work is done you say "lets not do it".
And If I knew you have arguments against it - I wouldn't do this PR.

Let me remind that:
image

My idea is that by changing from 4 spaces to 2 we make it easier for us to write ELM code that fits in 80 chats and thus conforms with the official style guide. 

In fact, just by bulk-reformatting our code with this forked `elm-format` we automatically make idk how many percents (30%? 50%) of our existing codebase style-guide compliant!


> The beauty of elm-format is that 99% of the elm users/packages use the same elm-format with zero configuration options.

So, I parse 2 important things here:

1. 99% of the elm users/packages use the same elm-format.
2. elm-format with zero configuration options.

After this PR is merged:

1.99% of the Elm users/packages will continue to use the same original elm-format so percentage won't change much if we're in 1% with our _private_ codebase.
2. elm-format and elm-format fork use zero configuration options: _no new configuration options introduced_

That means that current PR doesn't change the beauty (according your definition) in any way!


Anyway, @everlaat  - what's your suggestion? 
What should we do to save some horizontal screen estate?
How do we make sure that our code is ELM-idiomatic and fits 80 chars?

**Comment by michaelwebb76** [comment]
@Unisay I am satisfied

**Comment by everlaat** [comment]
> I am confused now:
> Here [tricycle/bellroy#3030](https://github.com/tricycle/bellroy/pull/3030) we agreed to fork `elf-format` and you didn't object, so I went ahead, spent time doing it and now, after the work is done you say "lets not do it".
> And If I knew you have arguments against it - I wouldn't do this PR.

I did object and after that I never received a notification on the state of the PR. I could have manually checked but I guess it slipped my attention

**Comment by everlaat** [comment]
It also doesn't help that all of the communication about this topic goes through Github, yet another channel besides Email, Slack and Asana and that decisions/approvals on this topic are then made outside Australian office times. 

I don't understand where the original ADR came from and I now feel like I missed my opportunity to say something about this what in my opinion is a none issue creating a lot more issues. This wasn't on my agenda and there were a lot of other things at the time of the original ADR that were more important to focus on.

The ADR starts with;
> Lets discuss the proposed ADR.
> Here is how my working setup looks like on laptop:

and

> I don't always have a widescreen and often work on 14" laptop.
>
> My IDE layout has
>
> - a file tree on the left,
> - editor or two side-by-side,
> - compiler running in terminal on the right.

I believe the majority of the Bellroy devs don't have this issue, and I don't see the benefit of us all now moving away from the standard enforced by `elm-format` to cope with this. 

This doesn't just affect our own private packages, public packages that we work on will have a "wrong" indented format unless we switch elm-format bins per project which just sounds another thing I prefer not to keep track of.

**Comment by Unisay** [comment]
> It also doesn't help that all of the communication about this topic goes through Github, yet another channel besides Email, Slack and Asana and that decisions/approvals on this topic are then made outside Australian office times.

Its a valid point that sometimes communication is split between Slack and Github PR (e.g. ADR).
The reason for it is that both mediums have desired properties:
* Slack is realtime and when working hours overlap - its possible to communicate with a higher thoughput.
* Github is async (no hight throughput) but it has other desired properties:
- Its close to the code; 
- It has a formal review/approval processes attached; 
- It stores our communication/decisions for future reference;

Based on that I follow a practice of:
- Talking on Slack when I need to get a quick answer and its relatively unimportant to record;
- Github PRs with ADR where its about decision to be made, and giving time and chance to all participants to study the topic asynchronously at their own pace;

I want to underline, that 

- no decision has been made via Slack, if you didn't read it - you didn't miss anything crucial, its optional  but convenient.
- the ADR with context, explanations and discussions is in place, it has been published there for quite a long time (28 days ago) and colleagues were commenting on it for 11 days.

You say that it doesn't help you that additional communication channel (#front-end-development) exists on Slack and in order to make life easier, are there any proposals that you want to make?
(I am ok if you ask people to limit communication about ADRs to github only. If this helps - I'd be following such discipline)

>  don't understand where the original ADR came from and I now feel like I missed my opportunity to say something about this what in my opinion is a none issue creating a lot more issues. This wasn't on my agenda and there were a lot of other things at the time of the original ADR that were more important to focus on.

I am sorry to hear it! Your input is valuable, I really wanted to hear more from you.
Is there anyting I can do better next time in this regard?

**Comment by everlaat** [comment]
Mate just merge it in. We're spending time and money on something so trivial compared to larger problems we could be tackling that I honestly feel terrible about it.

**Comment by michaelwebb76** [comment]
OK, it seems clear to me that there are good reasons not to proceed with the PR (and indeed the fork as a whole). Some of the benefit can be achieved just by asking everyone to ensure that their editor shows a margin and that we're incorporating an `elm-analyze` violation count in the code metrics (which has already been done).

On the subject of the communication channels and frustrations, a few things to say here:

- First and foremost, we put an enormous amount of effort into not hiring arseholes. Whenever we're reading textual messages to each other we should assume best intent. You are all working with a fantastic bunch of smart people with good intentions who get shit done. This was an attempt to improve a large part of our codebase for the benefit of everybody and I applaud that effort. Please be kind to each other and let's keep achieving amazing things, together.
- It _does_ make sense that changes to the content of our repositories, like ADRs for the purposes of having policy close to the place where it is implemented, should be discussed through Github in PRs. There are lots of notification options available to us to ensure we're aware of which open PRs require our attention (check out the Github Slack integration that shows you at a fixed time every day which open PRs you're specified as a reviewer/approver on).
- I think one of the things that went wrong here is that the original ADR PR was open so long that it fell off people's radars. I have a practice of reviewing open PRs once they've been open a few days and asking people to resolve them. In this case I think I directed @Unisay to proceed with the fork without taking the time to properly read the discussion just in order to get the PR closed off.

**Pull request closed without merging**
